project: 
  type: website
  output-dir: docs

website:
  title: "Giseok Kwon"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/username/username.github.io

  page-footer: 
    border: true
    left: "Giseok Kwon © 2024"
    right: 
      - icon: linkedin
        href: Your_LinkedIn_URL
      - icon: github
        href: https://github.com/username

  navbar:
    background: light
    search: false
    right:
      - text: "Home"
        file: index.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Competitions"
        file: competition.qmd

  sidebar:
    - title: "Full Stack"
      style: "docked"
      background: light
      contents:
        - text: "Overview"
          file: full_stack.qmd
        - text: "---"
        - text: "Project 1"
          file: Full_Stack/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Full_Stack/project2.qmd
        - text: "---"
    - title: "Competitions"
      style: "docked"
      background: light
      contents:
        - text: "Overview"
          file: competition.qmd
        - text: "---"
        - text: "Project 1"
          file: Competition/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Competition/project2.qmd
        - text: "---"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false